config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :definitions do
    collection do
      get :search
    end
  end

  root 'definitions#index'

end

app/models/definition.rb
class Definition < ActiveRecord::Base
  validates :word, presence: true
  validates :meaning, presence: true

  def fancy?
    self.word.length > 16
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:github]

    def self.from_omniauth(auth)
     user = where(provider: auth['provider'], uid: auth['uid']).first_or_create

     user.name         = auth.info.name
     user.email        = auth.info.email
     user.nickname     = auth.info.nickname
     user.access_token = auth.credentials.token
     user.password     = Devise.friendly_token[0,20]
     user.save!

     return user
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/definitions_controller.rb
class DefinitionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_definition, only: [:show, :edit, :update, :destroy]

  # GET /definitions
  # GET /definitions.json
  def index
    @last_time = session[:user_id]

    # session[:time] = Time.now.to_s

    @definitions = Definition.all
  end

  def search
    @search = params[:search]
    @definitions= Definition.where("word LIKE ?", "%#{@search}%")

    render :index
  end
  # GET /definitions/1
  # GET /definitions/1.json
  def show
    @definitions = Definition.find(params[:id])
  end

  # GET /definitions/new
  def new
    @definition = Definition.new
  end

  # GET /definitions/1/edit
  def edit
  @definitions = Definition.find(params[:id])
  end

  # PoST /definitions
  # POST /definitions.json
  def create
    @definition = Definition.new(definition_params)

    respond_to do |format|
      if @definition.save
        format.html { redirect_to @definition, notice: 'Definition was successfully created.' }
        format.json { render :show, status: :created, location: @definition }
      else
        format.html { render :new }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /definitions/1
  # PATCH/PUT /definitions/1.json
  def update
    respond_to do |format|
      if @definition.update(definition_params)
        format.html { redirect_to @definition, notice: 'Definition was successfully updated.' }
        format.json { render :show, status: :ok, location: @definition }
      else
        format.html { render :edit }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /definitions/1
  # DELETE /definitions/1.json
  def destroy
    @definition.destroy
    respond_to do |format|
    format.html { redirect_to definitions_url, notice: 'Definition was successfully destroyed.' }
    format.json { head :no_content }
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions
  def set_definition
    @definition = Definition.find(params[:id])
  end

  def definition_params
    params.require(:definition).permit(:word, :meaning, :word_type, :sentence ,:search)
  end


end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/definitions_helper.rb
module DefinitionsHelper
end

app/views/definitions/_form.html.erb
<%= form_for(@definition) do |f| %>
  <% if @definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@definition.errors.count, "error") %> prohibited this definition from being saved:</h2>

      <ul>
      <% @definition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :meaning %><br>
    <%= f.text_field :meaning %>
  </div>
  <div class="field">
    <%= f.label :word_type %><br>
    <%= f.select(:word_type,["noun", "verb", "adjective", "adverb"]) %>
  </div>
  <div class="field">
    <%= f.label :sentence %><br>
    <%= f.text_field :sentence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/definitions/edit.html.erb
<h1>Editing Definition</h1>

<%= render 'form' %>

<%= link_to 'Show', @definition %> |
<%= link_to 'Back', definitions_path %>

app/views/definitions/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Alien Language? Add it here!', new_definition_path %>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Meaning</th>
      <th>Word Type</th>
      <th>Word Used in a Sentence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @definitions.each do |definition| %>
      <tr>
        <td><%= definition.word %></td>
        <td><%= definition.meaning %></td>
        <td><%= definition.word_type %></td>
        <td><%= definition.sentence %></td>
        <td><%= link_to 'Show', definition %></td>
        <td><%= link_to 'Edit', edit_definition_path(definition) %></td>
        <td><%= link_to 'Destroy', definition, method: :delete, data: { confirm: 'Are you sure you want to send this word into a blackhole?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/definitions/new.html.erb
<h1>New Definition</h1>

<%= render 'form' %>

<%= link_to 'Back', definitions_path %>

app/views/definitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @definition.word %>
</p>

<p>
  <strong>Meaning:</strong>
  <%= @definition.meaning %>
</p>

<p>
  <strong>Word Type:</strong>
  <%= @definition.word_type %>
</p>
<p>
  <strong>Write a sentence using the word:</strong>
  <%= @definition.sentence %>
</p>

<%= link_to 'Edit', edit_definition_path(@definition) %> |
<%= link_to 'Back', definitions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsdictionary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1 id='text'><%= image_tag("logo.png", height: '75', width: '75')%>Space Jargon</h1>
     <nav class="navbar navbar-default navbar" role="navigation">
     <div class="container-fluid">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
       </div>
       <!-- Collect the nav links, forms, and other content for toggling -->
       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         <ul class="nav navbar-nav">
           <li><%= link_to "Login",  new_user_session_path %></li>
           <li><%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: 'Back to Earth?' } %></li>
           <li><%= link_to "Random Space Tongue",  new_user_session_path %></li>
           <%= yield :more_links %>
         </ul>
          <%= form_tag search_definitions_path, method: :get, class: "navbar-form navbar-left" %>
         <!-- <form class="navbar-form navbar-left" role="search" action="search_definitions_path" method="get"> -->
           <div class="form-group">
             <input type="text" name=':search' class="form-control" placeholder="Search">
           </div>
           <button type="submit" class="btn btn-default">Submit</button>
         </form>
       </div><!-- /.navbar-collapse -->
     </div><!-- /.container-fluid -->
   </nav>
  </header>

  <%= yield %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</body>
</html>